### ISSUE TITLE
Launch BitShares Developer Portal

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1031]
**Task List for dev.bitshares.works**
- [x] Define website structure (https://github.com/bitshares/dev.bitshares.works/blob/master/note.md)
- [x] Define page format (Markdown)
- [x] Define hosting environment (GitHub Pages)
- [ ] Update site content (@cedar-book @clockworkgr )
- [ ] Configure GitHub Pages (@clockworkgr )
- [ ] Launch to staging site
- [ ] Launch to dev.bitshares.works

**Assignees/Contributors**
* @clockworkgr 
* @cedar-book 

## CORE TEAM TASK LIST
- [ ] Refine Requirements/Task List (@ryanrfox @xeroc )
- [ ] Design / Develop Solution (@cedar-book )
- [ ] Perform QA/Testing
- [ ] PR to staging 
- [ ] PR to master (dev.bitshares.works)
