### ISSUE TITLE
No need to serialize `initial_chain_id` field when creating example genesis json?

### ISSUE THREAD

**Issue by cifer-lee** [bitshares/bitshares-core#1068]
I noticed that `create_example_genesis()` initialize the `initial_chain_id` to string "BOGUS"'s sha256 hash, while the generated genesis file will be entirely used by egenesis or by `--genesis-json` option to calculate the real chain id, the `initial_chain_id` field in the genesis file actually represents a wrong chain id.

It confused me a while, maybe not serialize the `initial_chain_id` field when creating example genesis? Since new devs&admins would mostly using example genesis as a base, this could confuse them too.

__Task List__
- [ ] Document workaround (reference #1069 )
- [ ] Fix within `Protocol Upgrade` release (this issue)
- [ ] Refactor documentation to match implementation

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
It's a hard fork change since serialization change will lead to different chain id. IMHO does not worth the efforts. To reduce confusion, we need documentation.

**Comment by ryanRfox** [comment]
@cifer-lee I attempted to split this Issue into something we can do now #1069 (document the as-is) and later, fix it in the code (#1068).

**Comment by pmconrad** [comment]
This is obsolete since we removed the `--create-genesis-json` option in #1529 . Closing.
