### ISSUE TITLE
CLI wallet: avoid directly overwriting wallet file on exit

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1109]
One of my wallet files got corrupted today due to disk full. Fortunately I have backed up the keys.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera 
  - [x] Estimated: 3 hours
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
#1050 is related.

**Comment by cogutvalera** [comment]
as an idea: to save wallet file with another filename something like `temp` wallet file or `backup`

**Comment by cogutvalera** [comment]
only on `exit` or in `save_wallet_file` ?

**Comment by abitmore** [comment]
`save_wallet_file`.

**Comment by cogutvalera** [comment]
my approximation/estimation is about 2 hours for this issue

**Comment by cogutvalera** [comment]
Thanks !

**Comment by cogutvalera** [comment]
rebased already

**Comment by ryanRfox** [comment]
Assigned to @cogutvalera and added estimate for 3 hours.

**Comment by abitmore** [comment]
Fixed by #1195.
