### ISSUE TITLE
Implement DPOS BFT— Pipelined Byzantine Fault Tolerance

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1144]
**User Story**
As a `Consensus Protocol` I want `to ensure the network will not fall out of consensus` due to `conflicting last irreversible blocks`.

**Additional Context (optional)**
eosio/eos/#2718 Describes the need to harden DPOS Protocol
Dan Larimer later wrote about the implementation of [DPOS BFT](https://medium.com/eosio/dpos-bft-pipelined-byzantine-fault-tolerance-8a0634a270ba) within EOSIO

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Related: #831

**Comment by clockworkgr** [comment]
Actually it seems EOS has not implemented BFT either (!!!).

Current version is not using BFT consensus: https://github.com/EOSIO/eos/issues/4965#issuecomment-410049124

and the relevant development issue has been blocked since April(??): https://github.com/EOSIO/eos/issues/2192
