### ISSUE TITLE
Proposed BSIPs for Stealth Development, Phase II

### ISSUE THREAD

**Issue by christophersanborn** [bitshares/bitshares-core#1214]
I am proposing the addition of **six new BSIPs** detailing the continued development of **“Stealth”** technology on the BitShares platform.  The six BSIPs subdivide the work into logically distinct components.

Initial drafts of these BSIPs including abstract and motivation are already written and are linked below.

### Background and motivation

“Stealth” here refers the ability of users to conduct certain activities privately, primarily the maintenance of private, inscrutable balances of any asset type, and the ability to transfer balances to other users without revealing value amounts or the identities of the parties involved.

Privacy, and therefore “Stealth,” is not a single technology or protocol, but rather several, that address specific mechanisms by which information about a user’s activities may be leaked. An initial round of Stealth development succeeded in implementing Confidential Transactions (CT) in March of 2016 following [BSIP-0008](https://github.com/bitshares/bsips/blob/master/bsip-0008.md).  CT provides two major features: value-blinding and stealth addresses.  These features, while important, are still very susceptible to chain analysis.  This is because inputs and outputs to a transaction are explicitly listed, meaning that for any particular output, a detailed history can be constructed, back to the originating transactions where a public balance was blinded.  Unless a user transacts with a large number of other users utilizing the Stealth features, the set of originating transactions in an output’s history may be small and highly likely to identify the user (or a small number of users) and suggest plausible value amounts.  In fact, casual users of Stealth may be receiving little to no privacy benefit from the features as currently implemented.

Thus, additional features and measures are still required to provide acceptable levels of privacy to the users of the Stealth feature.

Towards that end, I have written rough drafts of six BSIPs addressing specific components of continuing Stealth development, which, taken together, will result in an enormous increase in privacy afforded to the users of Stealth features on the BitShares platform.  These are still early drafts, and in some cases only partially complete, if not mere stub articles.  In some cases, there are more than one available solution to a particular problem, and involvement and discussion from the developer community is needed to ensure the best path forward is chosen.  Further research and documentation is needed to complete the BSIPs to the level where a decision on whether to implement can be made.

### The BSIPs

The proposed drafts are currently housed in @Agorise’s fork of the BSIPs repository.  The first BSIP serves as an entry point and summary of the remaining BSIPs and is located here:

https://github.com/Agorise/bsips/blob/master/bsip-1200.md

A table of all six BSIPs describing the specific components is located in the above link, and also replicated below: (Numbers are mere placeholders.)

Number             | Title                                                        | Type
:-----------------:|--------------------------------------------------------------|------------
1200 | Stealth development, Phase II           | Informational | Draft
1201 | New operations for Confidential Asset (CA) transactions    | Protocol
1202 | Ring signatures for untraceability of Stealth transactions | Protocol
1203 | Blockchain scanning for inbound Stealth transactions       | Protocol
1204 | Deterministic addresses for Stealth wallets                | Informational
1205 | Metadata hiding via Garlic Routing and other means         | Informational

### Work to be done:

I would personally like to take the lead on the completion of these drafts and thereafter on the implementation of the features.

Most of the BSIPs above include an abstract and motivation section.  Broad description of the proposed solutions are included, but the detailed specifications are still to be drafted.  I propose to do the necessary research to articulate solutions to the level of detail needed to allow committee assessment and implementation, should the community wish to implement.

For cases where more than one good solution may exist, I propose to research and draft concise summaries of available options to allow comparative evaluation.

## CORE TEAM TASK LIST
- [ ] BSIPs
  - [ ] Stealth development, Phase II
    - [x] Draft: @christophersanborn 
    - [ ] Review, refine, publish @bitshares/core-dev 
    - [ ] Submit BSIP for Community approval
  - [ ] New operations for Confidential Asset (CA) transactions
  - [ ] Ring signatures for untraceability of Stealth transactions
  - [ ] Blockchain scanning for inbound Stealth transactions
  - [ ] Deterministic addresses for Stealth wallets
  - [ ] Metadata hiding via Garlic Routing and other means
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
Great initiative @christophersanborn Thank you for taking this on for research and drafting of the BSIPs. I'm going to assign you to this Issue, representing the Epic for drafting the required BSIPs. I feel it will be best to create a new Epic to represent the implementation, when it progresses to that point. 

For now, I'll work with the Core Team to review the Informational overview BSIP and get the BSIP numbers assigned. We will also work together to determine estimations for drafting each BSIP, rather than for the lot. We are not estimating for implementation at this time.

**Comment by abitmore** [comment]
I think it's better to host this discussion in the bsip repository.

**Comment by pmconrad** [comment]
Has been moved to https://github.com/bitshares/bsips - closing.
