### ISSUE TITLE
Hardware Wallet Support (General)

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1339]
**User Story**
As a `user` I want `hardware wallet support` to store my private key(s) offline so that I may `sign a serialized transaction and submit it to the network`.

This is an Epic used to link to User Stories for specific implementations of various hardware wallet products. 

**Related User Stories (Core)**
- [ ] Ledger Nano S Hardware Wallet Support
- [ ] Ledger Nano Blue Hardware Wallet Support
- [ ] Trezor Hardware Wallet Support
- [ ] Trezor Model T Hardware Wallet Support

**Related User Stories (UI)**
 - [ ] TBD

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
Where in bitshares-core would you see the hardware wallets fitting in? 

The obvious one is the cli_wallet. But is there something that core could do to help the UI folks? I thought key storage and use was more a UI function than a core function.

Would you also expect to see that used for witness keys? I do not know how that would work.

**Comment by oxarbitrage** [comment]
In current core team worker proposal there are mentions of hardware wallet support IIRC. I suppose this and the related issues will allow to keep track of progress and allow funding from core worker even if the development is not a fully core thing. 
My 2 cents, @ryanRfox should be able to confirm this.

**Comment by ryanRfox** [comment]
@oxarbitrage is correct: I am trying to add Issues for development based on the original WP Development Initiatives. I agree with both @jmjatlanta and @abitmore that hardware wallet support (and others recently added) may not require any modifications to the `bitshares-core` repo. My intention for adding these within this repo it gain some visibility for the community to see what we intend to work on and solicit capable developers for contribution under the Community Claims section of the WP. I feel this is my best current option to track community contributions. I remain open to defining a process for doing it differently.
