### ISSUE TITLE
add fail_reason to reflection meta

### ISSUE THREAD

**Issue by dot5enko** [bitshares/bitshares-core#1730]
**Bug Description**
fail_reason field of proposal_object is not added to [proposal_object.hpp](https://github.com/bitshares/bitshares-core/blob/58c0c494a61c33e5a4ec2312084322f0014b4f5b/libraries/chain/include/graphene/chain/proposal_object.hpp#L102)  FC_REFLECT_DERIVED meta so RPC `get_object` results lacks that info

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Ouch. Thanks.
This should be fixed in the upcoming feature release.

**Comment by pmconrad** [comment]
Fixed by #1732
