### ISSUE TITLE
Review all APIs, add new optional parameters and change some old parameters to optional

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1766]
**User Story**
We'll soon support optional parameters for APIs (https://github.com/bitshares/bitshares-fc/pull/126), so we can update existing APIs to be more user-friendly.

For example, `get_call_orders` API now has two parameters, `asset` and `limit`, a user have to specify a limit, and can only query for the first page. If we change `limit` to optional and have a default value for it, users can simply call `get_call_orders(asset)` to fetch the top results; if we add an optional `start`, then users will be able to fetch next pages.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation
