### ISSUE TITLE
Add API for account history plugin to update tracking accounts and registrars

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2657]
**User Story**

Mentioned by Mike (codinheim) in the BitShares Development Telegram group ([link](https://t.me/BitSharesDEV/5797)):
> Is there a way to add an account's history to the node, equivalent to using `--track-account`, via a REST API call?  Or would I need to restart the node?
> My goal is to configure my BTS node to only download account histories for accounts that I care about. And its purpose will be to support the mobile wallet I'm releasing I need to add new users to the BTS node's account history on the fly.

I think if we are about to add an API to add tracking account, we can add an API to add tracking registrars too.

And probably also need an API to stop tracking an account or a registrar.

Another potential feature requirement is that node operators may want to keep references to added accounts, rather than stop tracking them across node restarts, i.e. configuration persistence.
- and what if the node is restarted with `--replay-blockchain` or `--resync-blockchain`?

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [x] Other (please add below)
  - Account history plugin

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation
