### ISSUE TITLE
Enable Travis-CI for automated builds

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#742]
**Requirements**
===========

* Ability to automate build process (Ubuntu) and execute test scripts following a GitHub commit using a third-party service (Travis-CI)
* Ability to display build status within GitHub repository (on README.md file as an icon)
* Note: the BitShares UI Team uses this integration within their repo today

**Tasks**
======

* [x] Demonstrate integration/functionality using a forked repo (https://travis-ci.org/ryanRfox/bitshares-core)
* [x] Create a branch on bitshares-core (https://github.com/bitshares/bitshares-core/tree/travis-ci)
* [x] Enable Travis-CI on bitshares/bitshares-core repo (Must be Admin: @abitmore @dnotestein @svk31 @xeroc )
  * [x] Step 0: Review Travis-Ci 'getting started guide' : https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI
  * [x] Step 1: Login to travis-ci.org using GitHub credentials
  * [x] Step 2: Enable `bitshares/bitshares-core` repo
  * [x] Step 3: Add a properly configured `.travis.yml` file to the `travis-ci` branch
  * [x] Step 4: Trigger the automated build by making a trivial commit within the `travis-ci` branch
  * [x] Step 5: Observe the build status icon on the `README.md` file within the `travis-ci` branch

**Comment by abitmore** [comment]
Have to expose personal data to another service? I personally don't like that..

**Comment by svk31** [comment]
I use encrypted access tokens for bitshares-ui, should be all you need.

**Comment by abitmore** [comment]
@ryanRfox I logged into Travis-CI, but it doesn't recognize that I'm in the `bitshares` organization. @svk31 any hint?

**Comment by abitmore** [comment]
Update: now I see it. It seems it just needs more time to sync my data.

**Comment by abitmore** [comment]
@ryanRfox seems it's done?

**Comment by ryanRfox** [comment]
Yes @abitmore the functionality is now working on the travis-ci branch. Thank you and to @svk for enabling this.

I will modify the README.md file in the travis-ci branch to include build icons for both the master and develop branches, then add a PR to the develop branch. 

We need to determine how we handle the status icon(s) within the README.md file in master. We can modify the file file manually to ensure the single build icon references the proper branch, or we can add a second icon and display for both master and develop.

**Comment by xeroc** [comment]
Referring to this ticket on travis:
https://github.com/travis-ci/travis-ci/issues/6300

**Comment by abitmore** [comment]
In short, check this file for enabling other (more recent) compilers: https://github.com/boostorg/hana/blob/master/.travis.yml

**Comment by oxarbitrage** [comment]
done.
