### ISSUE TITLE
Change hard-coded limitations in API's to configurable

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#782]
Change those `FC_ASSERT( limit <= 100 )` limitations to configurable. Inspired by https://github.com/bitshares/bitshares-core/issues/781#issuecomment-375962114.
- [ ] change them to configurable
- [ ] add API to fetch the configured values (https://github.com/bitshares/bitshares-core/issues/626)
- [ ] add restricted API for service providers to change the values on the fly (without restarting the server)
  - [ ] maybe remember changed value. Not easy since we're using (almost) read-only `config.ini` and startup parameters right now.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [x] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @manikey123
    - [x] 1. Change them to configurable
      - [x] Research and development (for point 1,2) 2 hr
      - [x] Review 1478 - fixes , testcases, node start 5.5 hr
      - [x] Review 1513 - rewrite testcase and revision 2 hr
      - [x] get_account_history - testcase and code 1.5 hr
      - [x] get_grouped_limit_orders - API research , testcase and implement 2.5 hr
      - [x] get_relative_account_history testcase and code 1 hr
    - [x] 2. Add API to fetch the configured values (#626)
      - [x] get_key_references should not subscribe to related accounts( (Issue 1472) #1499) 3 hr
      - [x] get_account_history_by_operations 1 hr
      - [x] get_asset_holders 2 hr
      - [x] review 1513 again for above Point2 1 hr
    - [ ] 3. Add restricted API for service providers to change the values on the fly
      - [x] Research 3.5 hrs
      - [x] Run 6 test cases for restarting configfile 1 hr
      - [x] Debugged main program and code map 3 hr
      - [ ] Partial completion, on hold pending decision https://github.com/bitshares/bitshares-core/issues/782#issuecomment-453104439
    - [x] Estimated:
      - [x] 1. 12 hours
      - [x] 2. 9 hours
      - [x] 3. 13.5 hours 
    - [ ] Remittance: 
      - [x] 1. 14.5 hours - Week 52
      - [x] 2. 7 hours - Week 5
      - [x] 3. 7.5 hours - Week 5
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
If rewriting config.ini while the node is running is scary, you may consider writing such settings to a new file, and doing a merge on the next startup.

**Comment by manikey123** [comment]
I’m going to claim this @ryanRfox

**Comment by ryanRfox** [comment]
Glad to have you take this on @manikey123. May I request you begin by offering an estimation for an implementation? It looks like this Issue may have at least one child Issue. You may consider investigating and claiming #626 and #1407 as well. I just need an estimation for each issue you claim. Thanks in advance for your assistance.

**Comment by manikey123** [comment]
By going through the code, the config.init file is used by the running node. So do not think it can be modified as it would be in read only mode. 
Considering non-file based approach and researching that. 2 hours estimated.

**Comment by manikey123** [comment]
When bitshares local node starts, plan is to push the config file into memory location say temp table part of database ( for example sql lite )
when node is running, if some one needs to edit the config file , currently readonly, instead the values is pushed into the database tables
when node is running to update configuration, use shell scripts that has update query having new information
Question : is there need to save the temporary table as when node stops the temp table gets dropped as per sqllite
If configuration needs to exist, i can make normal table
Let me know feedback so as to proceed implementation.

**Comment by pmconrad** [comment]
An additional database is overkill for this issue. Please find a simpler solution.

**Comment by manikey123** [comment]
-Part1
Assume original config file is parsed by validator function successfully. Hence local node up and running
Need Mutex for parsing to avoid race condition

-Part2
Values of config file go into stack memory. Advantage of using stack memory over heap memory is that it would stay alive as long as node is running
Timestamp of config file is also stored into stack memory
Referencing memory values will help us not access the config file, hence user can edit it when running

-Part3
Config file values can be updated and or new insertions take place
To identify these changes, we can use cross-platform libraries such as:
https://code.google.com/archive/p/simplefilewatcher/
https://github.com/emcrisostomo/fswatch

-Part4A - New Config values pass
Happy path. Repeat Part1
Question : old config values are available as long as node is running. Do we need to archive these ?

-Part4B - New Config values fail
Two options : 
Log failure result
Restore original configuration and Discard the change 

Feel free to enhance or suggest on above

**Comment by manikey123** [comment]
any feedback on this approach ?

**Comment by pmconrad** [comment]
1: Please optimize for the typical case, i. e. the config hasn't changed. Not sure if a mutex is the best choice.

2: I'd think that having the active config in heap and accessing through shared_ptr is simpler - that way you don't need to keep track of who is still using the old config after an update. The shared_ptr takes care of that. But feel free to implement as you see fit.

3: No additional 3rd-party-libraries please. This task is too simple to justify the additional burden.

4A: no, when new config takes effect the old config can be discarded

4B: Both - log the failure and continue to use old config

**Comment by mansiiyengar** [comment]
1: Please optimize for the typical case, i. e. the config hasn't changed. Not sure if a mutex is the best choice.
- I shall first focus on building typical case
2: I'd think that having the active config in heap and accessing through shared_ptr is simpler - that way you don't need to keep track of who is still using the old config after an update. The shared_ptr takes care of that. But feel free to implement as you see fit.
- Will explore shared_ptr approach 

3: No additional 3rd-party-libraries please. This task is too simple to justify the additional burden.
-For tracking timestamp of config file which is not third party, I shall use below : https://code.google.com/archive/p/simplefilewatcher/

4A: no, when new config takes effect the old config can be discarded
-ok
4B: Both - log the failure and continue to use old config
-ok

**Comment by manikey123** [comment]
1: Please optimize for the typical case, i. e. the config hasn't changed. Not sure if a mutex is the best choice.
- I shall first focus on building typical case

2: I'd think that having the active config in heap and accessing through shared_ptr is simpler - that way you don't need to keep track of who is still using the old config after an update. The shared_ptr takes care of that. But feel free to implement as you see fit.
- Will explore shared_ptr approach 

3: No additional 3rd-party-libraries please. This task is too simple to justify the additional burden.

- For tracking timestamp of config file which is not third party, I shall use below : https://code.google.com/archive/p/simplefilewatcher/

4A: no, when new config takes effect the old config can be discarded

- ok

4B: Both - log the failure and continue to use old config

- ok

**Comment by manikey123** [comment]
@pmconrad @ryanRfox : let me know if I can start implementation

**Comment by ryanRfox** [comment]
@manikey123 Please comment with your effort hours estimates for each Task in your list. You included them to me directly elsewhere, but we need them herein for transparency and for @pmconrad to review and provide additional feedback to me. 

I'm going to increase the research estimate to 3.5 hours (from 2) based on suggestions @pmconrad provided you and the adaptations you have considered. Thank you.

**Comment by manikey123** [comment]
High level implementation estimate (not started)
-Part1 - typical case - 3 hours
Assume original config file is parsed by validator function successfully. Hence local node up and running
Need Mutex for parsing to avoid race condition

-Part2 - shared_ptr approach - 4 hours
Values of config file go into stack memory. Advantage of using stack memory over heap memory is that it would stay alive as long as node is running
Timestamp of config file is also stored into stack memory
Referencing memory values will help us not access the config file, hence user can edit it when running

-Part3 - tracking timestamp wrapper -2 hours
Config file values can be updated and or new insertions take place
To identify these changes, we can use cross-platform libraries such as:
https://code.google.com/archive/p/simplefilewatcher/
https://github.com/emcrisostomo/fswatch

-Part4B - New Config values fail - log the failure and continue to use old config -1 hour
Two options :
Log failure result
Restore original configuration and Discard the change

**Comment by pmconrad** [comment]
No additional libraries please. You can use `std::filesystem::last_write_time` to detect changes.

**Comment by manikey123** [comment]
ok. thanks.

**Comment by manikey123** [comment]
bitshares account id = betas-11

**Comment by manikey123** [comment]
getting familiar and going through code that interacts with config ini

**Comment by manikey123** [comment]
1.Program Flow for First load -> configuration options are stored in memory.
1A> 
programs/witness_node/main.cpp
![image](https://user-images.githubusercontent.com/22608398/50138496-b0026980-0253-11e9-9147-2c4b251d5370.png)

1B>
At line 73 - Plugins set the remaining 35 options
![image](https://user-images.githubusercontent.com/22608398/50138521-b7c20e00-0253-11e9-9c30-e8658b11f025.png)


1C>
set program options sets the other 15 options
total there are 50 configurations
![image](https://user-images.githubusercontent.com/22608398/50138532-bee91c00-0253-11e9-9e33-ca34907c12ec.png)

1D>
Check is made if Config.ini exists or not. As this is first load, config.ini does not exist --> config.ini is created from configuration option --> sharepointers values are loaded and on successful validation, node is established

![image](https://user-images.githubusercontent.com/22608398/50138536-c4466680-0253-11e9-86fd-d707be21a507.png)






2>
Second load --> detected based on change in config.ini. Here comparison is made of share pointer values of first and second load. now second load items are considered and if validated successfully, this is considered the new config.ini

3>Clarifications / Inputs Needed:
1. second load : is testing needed on new sharepointer changed values ? is that in scope or out of scope ?
2. I seek to add timestamp as configuration option for reading and tracking purpose. Now when the new config file changes, the timestamp changes via std::filesystem::last_write_time . What is recommended place to add this time tracker loop which checks for timestamp change , there I will again call the load function
3. Seek to debug share_pointer in debugger. I get error message → RTII share pointer not found

Need to debug share ptr values part of issue 782

In main.cpp, line 65
bitshares-core/programs/witness_node/main.cpp

app_options.add_options()
    ("help,h", "Print this help message and exit.")
    ("data-dir,d", bpo::value<boost::filesystem::path>()->default_value("witness_node_data_dir"), "Directory containing databases, configuration file, etc.")
    ("version,v", "Display version information")
    ;

I tried approach gdb and I get the below error
(gdb) print *(app_options.m_options._M_impl._M_start)@1 
$1 = {{px = 0x561dfcf15d60, pn = {pi_ = warning: RTTI symbol not found for class 'boost::detail::sp_counted_impl_p<boost::program_options::option_description>'
0x561dfcee58d0}}}
(gdb) p $1.px.get()
Couldn't find method boost::shared_ptr<boost::program_options::option_description>::element_type::get
(gdb) p *$1.px.get()
Couldn't find method boost::shared_ptr<boost::program_options::option_description>::element_type::get
(gdb) p $1.*px.get()
No symbol "px" in current context.
(gdb) p $1.px._M_ptr
There is no member named _M_ptr.
(gdb) p $1
$2 = {{px = 0x561dfcf15d60, pn = {pi_ = warning: RTTI symbol not found for class 'boost::detail::sp_counted_impl_p<boost::program_options::option_description>'
0x561dfcee58d0}}}

Can anyone help me debug the above approach or suggest a better approach

**Comment by pmconrad** [comment]
> second load : is testing needed on new sharepointer changed values ? is that in scope or out of scope ?

My idea would be to encapsulate all the config handling and reloading in a class of its own. One instance of that is created on startup and handed over to plugins and application. Existing code should simply continue to use the configuration values from application start, i. e. making all these reloadable is out of scope. You only need to add the testing that you require for the API limits.

> What is recommended place to add this time tracker loop which checks for timestamp change

You can create an async task that executes the check and re-adds itself as its last step. See https://github.com/bitshares/bitshares-core/blob/2.0.181127/libraries/net/node.cpp#L4118-L4127 for examples.

It looks like your trying to debug Boost internal data structures. I've never tried that. You may be looking in the wrong place. What are you trying to find?

**Comment by manikey123** [comment]
Uploaded code for review : https://github.com/bitshares/bitshares-core/pull/1478

Focusing on these two areas for now in the code:
1.	change them to configurable
2.	add API to fetch the configured values (#626)

Code development covers below scenario:
Create a max account history operations limit. This link is configuration.
Default value is 100. It can be changed, I have changed this to 300 by changing value in config file.

Clarifications:
1.
On running function get_account_history_operations located in file history_api_test.cpp, config.init file is not loaded , can you suggest any approach to test the API ? 
![image](https://user-images.githubusercontent.com/22608398/50279955-0f04e180-0400-11e9-9af1-641f9ff69db1.png)

2. 
I am using ilog function for debugging the shared_pointers as I face BOOST error for the RTTI symbols not found. In my company the team uses CLION IDE with GDB and found it to be more time-saving than ilog. I am open for any better way to debug and open to connect with any technical member for the same.

**Comment by manikey123** [comment]
Request is to divide 782 into two tickets to manage the code. One is existing 782 and considering creating new ticket for below. Let me know.

Scope of existing 782 ticket :
1. change them to configurable
2. add API to fetch the configured values (#626)
3. get_key_references should not subscribe to related accounts (Issue 1472) #1499
  
Request to create new ticket for below as it is independent in nature
1.add restricted API for service providers to change the values on the fly (without restarting the server)
  maybe remember changed value. Not easy since we're using (almost) read-only config.ini and startup parameters right now.

**Comment by manikey123** [comment]
> Agree to handle config-changing API in a separate ticket. Not sure if this is a necessary feature though - node restart should be fast with the recent performance improvements.
> 
> Does anyone have info how long a restart (without replay) takes for a node with some history?

From my side, I tried using the database approach that digital lucifier had provided on telegram group. this took more than two hours for syncing the ledger. this was not even 10% completed. This was for node without replay.

**Comment by pmconrad** [comment]
My question was meant to be about restarting a fully synched node, in order to determine how much restarting for a config change hurts. One answer from telegram channel was 4 minutes I think.

Several telegram members agreed that an API for config changes without a restart would be "nice to have but not very important". It was a very small samle though. Nothing to base a decision on.

**Comment by manikey123** [comment]
Completed 
get_account_history_by_operations
get_asset_holders 

Uploaded code for review PR: #1513 

Remaining item yet to start: get_key_references should not subscribe to related accounts( (Issue 1472) #1499)

**Comment by manikey123** [comment]
@jmjatlanta can u explain the relation between this ticket and #782 and what needs to be done?

**Comment by ryanRfox** [comment]
Added this to our (next) Feature Release to get some eyes on this.

**Comment by bitfag** [comment]
What about `get_order_book` API call? It has a hardcoded limit `FC_ASSERT( limit <= 50 );`

**Comment by ryanRfox** [comment]
@bitfag I added `get_order_book` to #783 for review/implementation.

**Comment by manikey123** [comment]
Estimated 3 hrs to fix the code breakage caused due to code merge/ integration
Already spent 2 hrs

Made unsigned int changes on the test cases below:
 api_limit_get_account_history_operations
 api_limit_get_account_history
 api_limit_get_relative_account_history
 api_limit_get_account_history_by_operations
 api_limit_get_key_references

Below are the breakages due to plugin updates:
 api_limit_get_grouped_limit_orders

Below api input parameters are changed
 api_limit_get_asset_holders


- Are there any more new changes to the config options that need to be factored based on code merge/integration ?
- To prevent recurrence, recommendation is to update entire code in #783 and merge immediately
Any better suggestions, let me know

**Comment by manikey123** [comment]
Integration bug identified for API get_grouped_limit_orders
Solution : Use _app.enable_plugin("grouped_orders");
Clarification needed for the solution : What place should the solution line be placed at ? In test case or API ?
![image](https://user-images.githubusercontent.com/22608398/52898881-61604580-3198-11e9-8d8a-13bb9b93422f.png)

@pmconrad @jmjatlanta

**Comment by pmconrad** [comment]
Please enable in database_fixture for the specific test case, similar to https://github.com/bitshares/bitshares-core/blob/test-2.0.190212/tests/common/database_fixture.cpp#L146

**Comment by pmconrad** [comment]
Implemented via #1513 - @cedar-book please check if the config file documentation needs to be updated with the new parameters. https://github.com/manikey123/bitshares-core/blob/78cb2c7c7d4c417602ba51c0d429e3e4af408e97/libraries/app/application.cpp#L1006-L1019

**Comment by cedar-book** [comment]
@pmconrad, Okay. Yes, I will check into that.

**Comment by cedar-book** [comment]
@pmconrad, updated: [config example information](https://dev.bitshares.works/en/master/development/apps/node_config_example.html#examples)

**Comment by pmconrad** [comment]
Thanks!
