### ISSUE TITLE
[DEMO] Create Labes for Issue Management

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#820]
As a `Core Team Member` I need to `quickly identify attributes of an Issue ` to `convey relevant groups, status, etc.` to the Core Team and Community.

- [x] Create Labels as defined in the [Contribution Guide](https://github.com/bitshares/bitshares-core/wiki/Contribution-Guide)Wiki page

Reference these Tasks
- #823 Solicit feedback from Core Team Members
- #824 Solicit feedback from Community Members
- #825 Revise Labels based on feedback 
- #826 Incorporate feedback into Wiki page

**Comment by ryanRfox** [comment]
I wanted to create some Tasks for other Assignees to do, rather than use the original inline task list:

- [x] Create Labels as defined in the [Contribution Guide](https://github.com/bitshares/bitshares-core/wiki/Contribution-Guide)Wiki page
- [ ] Solicit feedback from Core Team Members
- [ ] Solicit feedback from Community Members
- [ ] Revise Labels based on feedback 
- [ ] Incorporate feedback into Wiki page 

So, I created four (4) new Issues, labeled them as "1c Task", then came back to this Issue to update the task list by referencing the other issues. You can just use the hash tag (#) to reference another Issue.

Go on, try it yourself.

**Comment by ryanRfox** [comment]
Now I want to close this User Story because I have completed the primary Task of creating the Labels. I already created and assigned the remaining Tasks, so I can update the Description from its current state:
- [x] Create Labels as defined in the [Contribution Guide](https://github.com/bitshares/bitshares-core/wiki/Contribution-Guide)Wiki page
- [ ] #823 Solicit feedback from Core Team Members
- [ ] #824 Solicit feedback from Community Members
- [ ] #825 Revise Labels based on feedback 
- [ ] #826 Incorporate feedback into Wiki page 

to just:
- [x] Create Labels as defined in the [Contribution Guide](https://github.com/bitshares/bitshares-core/wiki/Contribution-Guide)Wiki page

Now I am free to close this Task. Doing so will automatically move the User Story to the "Done" column on the Project Board.
