### ISSUE TITLE
AppVeyor Automated Build Services for Windows Binaries

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#964]
**User Story**
As a `Windows User` I want `trusted binaries` so that I may `deploy the BitShares software without building from source`.

Related Tasks:
* #958 Provide Automated Build Services to Deliver Binaries for Target Platforms

**Task List**
* [x] Connect AppVayor to GitHub for the `bitshares-core` repo
* [ ] Build Configuration (https://www.appveyor.com/docs/build-configuration/)
  * [ ] Build pipeline
  * [ ] Configuring build
  * [ ] Build versioning
  * [ ] AssemblyInfo patching
  * [ ] NET Core `.csproj` files patching
  * [ ] Clone directory
  * [ ] Environment variables
  * [ ] Script blocks in build configuration
  * [ ] Installing additional software
  * [ ] Hosts entries
  * [ ] Build matrix
  * [ ] Rolling builds
  * [ ] Scheduled builds
  * [ ] Build Queue
  * [ ] Testing
  * [ ] Pull Request

**Additional Context (optional)**
* Currently the BitShares-Core Team provide binaries with each tagged release for both Windows and Linux. However, they could be produced in a more transparent way.
* The BitShares-UI Team uses AppVeyor for Windows binaries with each releases. This Issue intends to build upon their successes. 
* AppVeyor (https://www.appveyor.com/)
  * Build Environments (https://www.appveyor.com/docs/build-environment/):
    * Visual Studio 2013
      * Boost: 1.56, 1.58
      * OpenSSL: OpenSSL 1.0.2L
    * Visual Studio 2015
      * Boost: 1.60, 1.62, 1.63, 1.65, 1.66, 1.67
      * OpenSSL: OpenSSL 1.0.2L
    * Visual Studio 2017
      * Boost: 1.65, 1.66, 1.67
      * OpenSSL: OpenSSL 1.0.2L
 
## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
Assigned @cogutvalera for estimated 10 hours.

**Comment by ryanRfox** [comment]
Please see this [note](https://github.com/bitshares/bitshares-core/issues/1304#issuecomment-418207137) in #1304 about static linking, as it may provide insights for your solution.

**Comment by marcialvieira** [comment]
Hi @ryanRfox and everyone, I'm interested in working on this issue as a continuation of #985

**Comment by cogutvalera** [comment]
@marcialvieira welcome ! This will be cool when will be done !

**Comment by pmconrad** [comment]
1st shot for fc: https://github.com/bitshares/bitshares-fc/pull/128

**Comment by abitmore** [comment]
I think https://github.com/bitshares/bitshares-gitian can do the job already. Perhaps close this issue.
